apiVersion: v1
kind: Config
clusters:
- name: "ggggggggggg"
  cluster:
    server: "https://192.168.15.169/k8s/clusters/c-sgqql"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwekNDQ\
      VUyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpJdwpPREEzTVRReE1UVXhXaGNOTXpJd09EQTBNVFF4TVRVeFdqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNZbWJKcFZFaDFrR\
      VFnSFJzaUMvejFwck14b2pwaXBXTWJGMnlFZ05LSAp0VXpaejhCT3JMMnNreTN4WGoza0tHdGVVM\
      DdrUE05Mllud1VHSmVWamlNTG8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVNlg0dkZCR0V6dE1WZ2pQOTRoRlQKSUJLUENUa3dDZ\
      1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBT3JRWXQrYnNGc0RwaDdlR0xKb1dSN3RENnpMSENnOQpHR\
      mRBVzBydHh1cHpBaUI0Sk5KZjRwNU1OeDAxbFJCMWoyNHB6VWdKVFA2eW1NU0tlSThHdXJ2KzhRP\
      T0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
- name: "ggggggggggg-master"
  cluster:
    server: "https://192.168.15.170:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURnd056RTBNVGN6TUZvWERUTXlNRGd3TkRFME1UY3pNRm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU0vNnhpNlJUWk5CCjkwRkw1RGFKbGc0aEIyQUNpWW5INXh3d3UvUkFueUlHVHp6amVleXlLS\
      HZaNmZiYmhjc28xeXdOR3dPMVlxK1oKSGdiczRkT3FwNkRxOWVnVHNWaW1jWW1GRTFSdWMwUURmV\
      k8wb2M4eXE5OUVSTGpIRmUwelFPME9UWkZWSGxQeQpwWS9zeStxWktZNWJBNDNxVGVnT3VQZWpPM\
      U82REdteDQ5SHhESGJSQko2UHdoY0lXc3NTNEJ0OGVuUkY2L0JwCkFYQVhKKzVhRCtPRG9rV2pZb\
      kRkZ3ZFVkJVYVhteWxmRWswN3dJOXNMRlpxbzJOVzVSNEdCRjJQbHQxLzIwNDcKUStoUkM1REZ3Q\
      zYyN0o4Vmo4d2JBblJxOWg1V1RsWndRSWFNMnM5TG1WekNUSnlpeGl4bW5wYWwxejQ1RGozYwptR\
      mNEbnJwUzlhc0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGSG5UcThIWFZ3MGd5SlljQ1NEc0NEVEFZLzh4TUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQWYyQTVRWlJOOHFDSTJubTJWeGt4S1htdlhsNWFEUFNMZ3REM\
      lM0Nk5HL1FQWVIrRmFUdk9EZVZ0Ugo0cEdZZjJIVG12VDZkWmxaTTJQeGNnMCtXelVjeVlGc2dxW\
      ThUUkhvZi9yN0RYNDdKRUhJWURHbzNPRE1WcWhNCm5GSlJvcjRsNzhsMlNycGVxZjFjNnI0S1BJY\
      jBEZ1VYVGRSdkorTk1VRnFhUDAyWmJ5bzVLelZaeTlxMEJZOFoKVFBZRklzako2NUh3SUJSZXZ2T\
      kphV3RqSGt6d3lsVzZxbU5Wa3JocXdVbW1TNzk1V0c2Ym1kS0JjVDRJQ1IwegpuU0Y1Y2c5Y1ZKb\
      y94eUptb1ZOTDhqL1FWcjhlUUp5a0d6MENXeU4vUFd6alErN0hlSXJrSTRTL1Q5WlhwaHpSCjR3d\
      U9KbG95dlFDVSs4WGQ4aWd3TS9TaFBaQTcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "ggggggggggg"
  user:
    token: "kubeconfig-user-7wxjp27z9d:2v7cqrx986bg88hqxlrn9w6lb7l7k94wz69wwntd9qnmnk54fnbpbb"


contexts:
- name: "ggggggggggg"
  context:
    user: "ggggggggggg"
    cluster: "ggggggggggg"
- name: "ggggggggggg-master"
  context:
    user: "ggggggggggg"
    cluster: "ggggggggggg-master"

current-context: "ggggggggggg"
