apiVersion: v1
kind: Secret
metadata:
  name: apicurio-secret
  namespace: apicurio
type: Opaque
data:
  db-password: QXAxY3VyMW8wMA==
  db-root-password: QXAxY3VyMW8wMA==
  db-user: YXBpY3VyaW8=
  apicurio-kc-client-secret: M1dUQkppRnBEbDdPbmYxN0luU3BmTklTMFlBWTBpZmw=
  #apicurio-microcks-client-secret:
